<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="tohtml-q5.xsl"?>

<!DOCTYPE course [
     <!ELEMENT course (name, duration, unit+) >
     <!ELEMENT name (#PCDATA) >
     <!ELEMENT unit (title*, lecturer*, tutor*) >
     <!ELEMENT title (unitcode, unitname) >
     <!ELEMENT unitcode (#PCDATA)>
     <!ELEMENT unitname (#PCDATA)>
     <!ELEMENT lecturer (surname, othernames?, email*) >
     <!ELEMENT tutor (surname, othernames?, email*) >
     <!ELEMENT surname (#PCDATA) >
     <!ATTLIST surname language CDATA "English" >
     <!ELEMENT othernames (#PCDATA) >
     <!ATTLIST othernames language CDATA "English" >
     <!ELEMENT email (#PCDATA) >
]>

<course>
     <name>Bachelor of Science - Internet Computing</name>
     <duration>3 years</duration>
     <unit>
          <title>
               <unitcode>ICT375</unitcode>
               <unitname>Advanced Web Programming</unitname>
          </title>
          <lecturer>
              <surname language="English">Xie</surname>
              <othernames language="English">Hong</othernames>
              <email>h.xie@murdoch.edu.au</email>
          </lecturer>
     </unit>
     <unit>
          <title>
               <unitcode>ICT108</unitcode>
               <unitname>Introduction to Multimedia and the Internet</unitname> 
          </title>
          <lecturer>
              <surname>Rai</surname>
              <othernames>Shri</othernames>
              <email>s.rai@murdoch.edu.au</email>
          </lecturer>
     </unit>
</course>
